version: '3'

services:
  mysql:
    image: mysql:8.1
    container_name: docosan-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: tasks
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - docosan_network
      
networks:
  docosan_network:

volumes:
  database_data: